---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/vendorinfos":
    get:
      summary: list vendorinfos
      responses:
        '200':
          description: successful
    post:
      summary: create vendorinfo
      responses:
        '200':
          description: successful
  "/api/v1/vendorinfos/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show vendorinfo
      responses:
        '200':
          description: successful
    patch:
      summary: update vendorinfo
      responses:
        '200':
          description: successful
    put:
      summary: update vendorinfo
      responses:
        '200':
          description: successful
    delete:
      summary: delete vendorinfo
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
